title: "ScalaJack"
description: "Documentazione del progetto PPS-26 ScalaJack: implementazione in Scala del gioco da casinò Blackjack."
remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme
mermaid:
  version: "11.6.0"
aux_links:
  "Repository su GitHub":
    - "https://github.com/NicoForlivesi/PPS-26-scalajack"
